### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by mike-pete** [ntersol/react-starter#1]
Should we adjust the [naming convention](https://github.com/ntersol/react-starter#naming-convention-for-components) a bit? Instead of `index.ts` could we do `PascalCaseComponentName.tsx` for our components?

It could make navigating directly to a specific file a bit easier. Otherwise you could potentially have hundreds of `index.ts` files in a large project.

Note: `.tsx` shows that this is a TypeScript file that contains component code: https://reactjs.org/docs/introducing-jsx.html

**Comment by kid-on-github** [comment]
Also should the folders match the naming of the exported component as well?
